version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    time: 04:00
    timezone: Asia/Shanghai
  open-pull-requests-limit: 5
  groups:
    routine-version-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
    time: 04:00
    timezone: Asia/Shanghai
  open-pull-requests-limit: 5
  groups:
    routine-version-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    time: 04:00
    timezone: Asia/Shanghai
  open-pull-requests-limit: 5
  groups:
    routine-version-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    time: 04:00
    timezone: Asia/Shanghai
  open-pull-requests-limit: 5
  groups:
    routine-version-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
