permissions:
  contents: read

name: PR Title Spell Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  typos:
    name: Spell check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Store PR title in a file
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo $TITLE > pr_title.txt

      - name: Spell check
        uses: crate-ci/typos@b41eb62e9a8096c9ba6636e2365d3f56018a203c
        with:
          files: ./pr_title.txt
